### ISSUE TITLE
Arrange Files and Code

### ISSUE THREAD

**Issue by Karan-Dhingra** [Karan-Dhingra/Hacktoberfest-CPP#58]
Add all DS Code in DS Folder and Algo Code in Algo Folder. If having trouble finding out in which folder it will go skip that program.

**Comment by sharonibose** [comment]
@Karan-Dhingra, could you kindly assign me this task?

**Comment by Meghwantsingh** [comment]
Hello, i also like to add algorithm. Can I.

**Comment by c99SRS** [comment]
@Karan-Dhingra , can you please assign me?
